kind: pipeline
name: default

steps:
  
- name: Deploy
  image: alpine
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
  - apk update
  - apk add npm curl jq
  - npm install -g markdownlint-cli
  - echo \"{\"MD013\": false}\" > .markdownlint.json
  - markdownlint -c .markdownlint.json README.md
  - if [  "$(curl -s -H "Authorization:token $GH_TOKEN" https://api.github.com/repos/jmarhee/github-repo-practices | jq .homepage)" = "null" ]; then echo "No homepage link set."; exit 1; fi   
  - if [  "$(curl -s -H "Authorization:token $GH_TOKEN" https://api.github.com/repos/jmarhee/github-repo-practices | jq .description)" = "null" ]; then echo "No description set."; exit 1; fi 
  - if [  "$(curl -s -H 'Accept:application/vnd.github.mercy-preview+json' https://api.github.com/repos/jmarhee/github-repo-practices/topics | jq '.names | length' | xargs echo)" = "0" ]; then echo "No topics set."; exit 1; fi
